// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "QuanView",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "QuanView",
            targets: ["AppModule"],
            bundleIdentifier: "anshulkumaria1612-gmail.com.QuanView",
            teamIdentifier: "G3Y27UPJJ3",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .camera),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "QuanView uses the camera only to place experiments in your real-world space."),
                .locationAlwaysAndWhenInUse(purposeString: "QuanView records your location when saving experiment logs."),
                .locationWhenInUse(purposeString: "QuanView records your location when saving experiment logs.")
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)